package me.whizvox.myparkour.course.run;

import it.unimi.dsi.fastutil.objects.Object2ObjectArrayMap;
import it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap;
import me.whizvox.myparkour.MyParkour;
import me.whizvox.myparkour.course.Course;
import org.bukkit.GameMode;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.jetbrains.annotations.NotNullByDefault;

import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.logging.Level;

@NotNullByDefault
public class CourseRuns {

    private final Map<UUID, CourseRun> runs;
    private final Map<UUID, StoredRun> stored;

    public CourseRuns() {
        runs = new Object2ObjectOpenHashMap<>();
        stored = new Object2ObjectArrayMap<>();
    }

    public Optional<CourseRun> getRun(Player player) {
        return Optional.ofNullable(runs.get(player.getUniqueId()));
    }

    public Optional<StoredRun> getStoredRun(Player player) {
        return Optional.ofNullable(stored.get(player.getUniqueId()));
    }

    public boolean startRun(Player player, Course course, GameMode previousGameMode, ItemStack[] inventory) {
        if (runs.containsKey(player.getUniqueId())) {
            return false;
        }
        CourseRun run = new CourseRun(player, course, previousGameMode, inventory);
        runs.put(player.getUniqueId(), run);
        stored.put(player.getUniqueId(), run.store());
        return true;
    }

    public void update() {
        runs.values().forEach(CourseRun::update);
    }

    public Optional<CourseRun> stop(Player player, boolean disconnected) {
        var result = Optional.ofNullable(runs.remove(player.getUniqueId()));
        if (!disconnected) {
            stored.remove(player.getUniqueId());
        }
        return result;
    }

    public void save(Path filePath) {
        YamlConfiguration config = new YamlConfiguration();
        config.set("runs", stored.values().stream().toList());
        config.setComments("runs", List.of(
            "List of all active runs, specifically, all information needed to restore a player's state if they were to disconnect while running a course.",
            "Do NOT edit this file unless you know precisely what you are doing!"
        ));
        try (Writer writer = Files.newBufferedWriter(filePath, StandardCharsets.UTF_8)) {
            writer.write(config.saveToString());
        } catch (IOException e) {
            MyParkour.inst().getLogger().log(Level.WARNING, "Could not save disconnected runs at " + filePath, e);
        }
    }

    public void load(Path filePath) {
        if (Files.exists(filePath)) {
            try (Reader reader = Files.newBufferedReader(filePath, StandardCharsets.UTF_8)) {
                YamlConfiguration config = YamlConfiguration.loadConfiguration(reader);
                //noinspection unchecked
                List<StoredRun> disconnectedRead = (List<StoredRun>) config.get("runs", List.of());
                stored.clear();
                disconnectedRead.forEach(run -> stored.put(run.playerId(), run));
            } catch (IOException e) {
                MyParkour.inst().getLogger().log(Level.WARNING, "Could not load disconnected runs from " + filePath, e);
            }
        }
    }

}
